version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: my_redis
    command: redis-server --requirepass postgres
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=postgres
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: my_nest_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data: